spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/gramola_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Mailtrap Config (Development)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=66750283c6febd
spring.mail.password=f69c3d2b05bc03

# Stripe Config
stripe.api.key=sk_test_51SGRYtLYhxLLPwjraxqg3DDQj8zT9SmlI7HlFU8kvMd6z2b8YUIvBdTmhTDaFSQj5hFCchqweieNADVjcOw7fsWR00XwSBocF9

# Spotify Config
spotify.client.id=8a35a4032bbe4a299b23e84664ab9a56
spotify.client.secret=15a8f1bc39d4467d947d34f792028904

# App Config
app.frontend.url=http://127.0.0.1:4200
app.backend.url=http://127.0.0.1:8080

# PARA DEFENSA: 
# La configuración ddl-auto=update permite que Hibernate cree las tablas 
# automáticamente según nuestras entidades JPA. 
# Las credenciales de APIs externas están centralizadas aquí para facilitar 
# el despliegue en diferentes entornos (Desarrollo vs Producción).
